// Code generated by "stringer -type=QClass"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClassUnknown-0]
	_ = x[ClassIN-1]
	_ = x[ClassCS-2]
	_ = x[ClassCH-3]
	_ = x[ClassHS-4]
	_ = x[ClassAny-255]
}

const (
	_QClass_name_0 = "ClassUnknownClassINClassCSClassCHClassHS"
	_QClass_name_1 = "ClassAny"
)

var (
	_QClass_index_0 = [...]uint8{0, 12, 19, 26, 33, 40}
)

func (i QClass) String() string {
	switch {
	case i <= 4:
		return _QClass_name_0[_QClass_index_0[i]:_QClass_index_0[i+1]]
	case i == 255:
		return _QClass_name_1
	default:
		return "QClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
