// Code generated by "stringer -type RCode"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RCodeNoErrorCondition-0]
	_ = x[RCodeFormatError-1]
	_ = x[RCodeServerFailure-2]
	_ = x[RCodeNameError-3]
	_ = x[RCodeNotImplemented-4]
	_ = x[RCodeRefused-5]
}

const _RCode_name = "RCodeNoErrorConditionRCodeFormatErrorRCodeServerFailureRCodeNameErrorRCodeNotImplementedRCodeRefused"

var _RCode_index = [...]uint8{0, 21, 37, 55, 69, 88, 100}

func (i RCode) String() string {
	if i >= RCode(len(_RCode_index)-1) {
		return "RCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RCode_name[_RCode_index[i]:_RCode_index[i+1]]
}
